# Generated by Django 3.0.2 on 2021-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hcity', models.CharField(max_length=20)),
                ('hprize', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('himage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('pname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pcity', models.CharField(max_length=20)),
                ('pprize', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('pimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
