# Generated by Django 3.0.2 on 2021-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hdec',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pdec',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pdur',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='himage',
            field=models.ImageField(upload_to='himages/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pimage',
            field=models.ImageField(upload_to='pimages/'),
        ),
    ]
